version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: chatdb
    depends_on:
      - mysql

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000

volumes:
  mysql-data:
